name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Plan & Apply
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform init
        working-directory: ./application

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./application

      - name: Terraform Plan
        run: terraform plan -var-file=dev.tfvars -out=application.tfplan
        working-directory: ./application

      - name: Terraform Apply
        run: terraform apply -auto-approve application.tfplan
        working-directory: ./application